[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "pysco-nbody"
version = "0.3.5"
authors = [
    { name = "Michel-AndrÃ¨s Breton", email = "michel-andres.breton@obspm.fr" },
]
description = "A Python library to run N-body simulations with modified gravity"
readme = "README.md"
requires-python = ">=3.8, <3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy",
    "matplotlib",
    "astropy",
    "numba",
    "icc-rt",
    "pandas",
    "scipy",
    "pyarrow",
    "h5py",
    "rich",
    "pyfftw",
]

[project.urls]
Homepage = "https://github.com/mianbreton/pysco"
